services:
  postgres:
    image: postgres:latest
    ports:
      - '5455:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
       POSTGRES_PASSWORD: 123456
       POSTGRES_USER: root
       POSTGRES_DB: library_database
